Repository mjdocs/myJS, pull requests merged in 2024-08, with the labels that each got.

#17 MJ-15: update Introduction with new source and historical facts, fix minor bugs
  Introduction.md
  Methodology.md
  Preface.md
  get-started/Chapter_3.md
Labels: bug, documentation, enhancement

#19 MJ-16: update chapters structure through adding "docs" folder, add new future Realms chapter 5, rename operations chapter to records 4.0
  README.md
  docs/Introduction.md
  docs/Methodology.md
  docs/Preface.md
  docs/Realms.md
  docs/assets/chromium.png
  docs/assets/easy.svg
  docs/assets/ecma-big.png
  docs/assets/ecma-logo.svg
  docs/assets/ecma.png
  docs/assets/ecmaBg.jpg
  docs/assets/formal.svg
  docs/assets/hard.svg
  docs/assets/informal.svg
  docs/assets/js.png
  docs/assets/myJS.png
  docs/assets/normal.svg
  docs/assets/profile.png
  docs/assets/tc39.png
  docs/assets/v8.png
  docs/assets/whatwg.png
  docs/get-started/Chapter_1.md
  docs/get-started/Chapter_2.md
  docs/get-started/Chapter_3.md
  docs/get-started/Chapter_4.md
  docs/get-started/assets/grammar1.png
  docs/get-started/assets/grammar2.png
  docs/get-started/assets/grammar3.png
  docs/get-started/assets/grammar4.png
  docs/get-started/assets/grammar5.png
  docs/get-started/assets/img1.png
  docs/get-started/assets/img2.png
  docs/get-started/assets/img3.png
  docs/get-started/assets/parameter1.png
  docs/get-started/assets/parameter2.png
  docs/get-started/assets/parameter3.png
  docs/get-started/assets/parameter4.png
  docs/get-started/assets/type1.png
  docs/get-started/assets/type2.png
  docs/get-started/index.md
  docs/records/index.md
  operations/index.md
Labels: documentation, enhancement

#23 MJ-17: update CONTRIBUTING and CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  docs/Realms.md
Labels: documentation, enhancement

#25 MJ-18: add new images and delete unused, update README, remove incorrect time stamps
  README.md
  docs/Realms.md
  docs/assets/asforjs.png
  docs/assets/ecma-big.png
  docs/assets/ecma-logo.svg
  docs/assets/ecma.png
  docs/assets/ecmaBg.jpg
  docs/assets/js.png
  docs/assets/wiki.png
  docs/get-started/Chapter_3.md
  docs/get-started/Chapter_4.md
  docs/records/index.md
Labels: bug, documentation, enhancement

#26 MJ-19: specify context for Chromium blog, fix minor bugs
  docs/Methodology.md
Labels: bug, logical error

#30 MJ-20: update CONTRIBUTING file, fix typo and logical error
  CONTRIBUTING.md
Labels: typo, logical error, ready to merge

#31 MJ-21: add alternative resources part with links
  docs/Methodology.md
Labels: enhancement, ready to merge

#32 MJ-22: fix navigation bug between pages
  docs/Introduction.md
  docs/Realms.md
  docs/get-started/Chapter_1.md
  docs/get-started/Chapter_2.md
  docs/get-started/Chapter_3.md
  docs/get-started/Chapter_4.md
  docs/get-started/index.md
  docs/records/index.md
Labels: bug, ready to merge

#34 MJ-23: add new profile photo to README, update chapters 3 and 4
  README.md
  docs/assets/profile.png
  docs/get-started/Chapter_3.md
  docs/get-started/Chapter_4.md
  docs/records/index.md
Labels: docs improvement, logical error, ready to merge

#37 MJ-23: update code of conduct, add new image, update Methodology
  CODE_OF_CONDUCT.md
  docs/Methodology.md
  docs/assets/specialForces.png
Labels: docs improvement, enhancement, Special Forces

#27 Update README.md
  README.md
Labels: invalid, reject to merge

#44 MJ-26: update CONTRIBUTING rules, add new image, update Algorithm Chapter
  CONTRIBUTING.md
  docs/Methodology.md
  docs/Preface.md
  docs/get-started/Chapter_3.md
  docs/get-started/Chapter_4.md
  docs/get-started/assets/algorithm1.png
Labels: docs improvement, enhancement, ready to merge

#46 MJ-27: add all chapters block in the main index Chapters, add new Funarg Chapter 4.1, update README and Algorithm Chapter 3.4
  README.md
  docs/get-started/Chapter_4.md
  docs/get-started/assets/algorithm2.png
  docs/get-started/index.md
  docs/records/Chapter_1.md
  docs/records/index.md
Labels: enhancement, ready to merge

#52 MJ-30: fix minor bugs
  CODE_OF_CONDUCT.md
  README.md
  docs/get-started/Chapter_4.mdx
  src/components/BlockQuote/style.module.scss
  src/css/custom.css
  src/pages/index.mdx
Labels: docs improvement, enhancement, ready to merge

#53 MJ-31: add new About us page, fix minor bugs
  blog/2024-08-25-first-post.mdx
  blog/tags.yml
  docusaurus.config.ts
  package.json
  src/components/GithubStar/GithubStar.tsx
  src/components/GithubStar/style.module.scss
  src/css/custom.css
  src/pages/about/index.mdx
  src/pages/index.mdx
  static/img/github-dark.svg
  static/img/github-light.svg
  yarn.lock
Labels: bug, enhancement, ready to merge

#54 MJ-32: update About page, set order for action workflows
  .github/workflows/Deploy.yml
  .github/workflows/Test-deploy.yml
  src/components/Avatar/Avatar.tsx
  src/components/Avatar/style.module.scss
  src/pages/about/index.mdx
Labels: enhancement, ready to merge

#57 MJ-33: update main page, reset actions to previous state
  .github/workflows/Deploy.yml
  .github/workflows/Test-deploy.yml
  README.md
  docusaurus.config.ts
  src/components/GithubStar/style.module.scss
  src/components/Home/Home.tsx
  src/components/Home/style.module.scss
  src/css/custom.css
  src/css/mixins/_width.scss
  src/pages/about-us/index.mdx
  src/pages/index.mdx
  static/img/mainLogo.svg
Labels: docs improvement, enhancement, ready to merge
